[package]
name = "legit"
version = "0.0.0"
authors = ["Joel Söderman <joel.soderman@klarna.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
